# Generated by Django 4.1.7 on 2023-03-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('neck', models.FloatField()),
                ('arms', models.FloatField()),
                ('forearms', models.FloatField()),
                ('wrist', models.FloatField()),
                ('chest', models.FloatField()),
                ('stomach', models.FloatField()),
                ('waist', models.FloatField()),
                ('butt', models.FloatField()),
                ('thighs', models.FloatField()),
                ('calves', models.FloatField()),
            ],
        ),
    ]
