# Generated by Django 4.1.7 on 2023-03-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EODChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gym_workout', models.BooleanField(default=False)),
                ('reading_50_pages', models.BooleanField(default=False)),
                ('coding_half_hour', models.BooleanField(default=False)),
                ('quality_sleep', models.BooleanField(default=False)),
            ],
        ),
    ]
